table DJR_998
	lineageTag: e15fcdc7-26de-450a-8161-c7ef90e5ba04

	measure 'Total Processos' = COUNTROWS('DJR_998')
		formatString: 0
		lineageTag: c8fbe5d8-8657-412d-9ded-4c722c3b5198

	measure 'Processos Ativos' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "Ativo"
			)
		formatString: 0
		lineageTag: e1d8ae72-ab6c-4daf-b82b-d2150c67c5f9

	measure 'Processos Arquivados' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "Arquivado"
			)
		formatString: 0
		lineageTag: 5b68c85a-3085-47aa-bc2b-a08c8aa0944c

	measure 'Arquivado Cancelamento' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "arquivado por cancelamento da distribuição"
			)
		formatString: 0
		lineageTag: bd06bf44-4b4c-4f08-8302-b778529aedbe

	measure 'Arquivado provisoriamente' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "Arquivado provisoriamente"
			)
		formatString: 0
		lineageTag: 5e09aaf5-5b33-4fb3-a928-50b96f5c84c4

	measure 'inst superior' = ```
			
			 CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "Em instância superior"
			 )   
			```
		formatString: 0
		lineageTag: 83c6cac5-ff8f-4680-ad65-a48329ac07f1

	measure 'Suspenso ou sobrestado' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Status] = "Suspenso ou sobrestado"
			)
		formatString: 0
		lineageTag: 471379fd-05dd-4ff1-9664-dd73906b391e

	measure 'Ranking Vara' =
			
			RANKX(
			    ALL('DJR_998'[Vara]),
			    [Total Processos],
			    ,
			    DESC
			)
		formatString: 0
		lineageTag: 38a86961-591e-43d1-a974-a95346f796fa

	measure 'Tipo Cliente' =
			
			SWITCH(
			    TRUE(),
			    [Total Processos] >= 10, "Alto volume",
			    [Total Processos] >= 5, "Médio volume",
			    "Baixo volume"
			)
		lineageTag: 373e79bf-9c5b-40ab-afcf-158c392cf39c

	measure 'Processos Antigos Ativos' =
			
			CALCULATE(
			    COUNTROWS('DJR_998'),
			    'DJR_998'[Idade Processo] > 365,
			    'DJR_998'[Status] = "ativo"
			)
		formatString: 0
		lineageTag: c84468ff-06b2-4411-aa7d-9330e293a95e

	column 'Número do Processo'
		dataType: string
		lineageTag: 1733d967-3b59-4844-9f8c-098cd62e18f0
		summarizeBy: none
		sourceColumn: Número do Processo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Número Antigo'
		dataType: string
		lineageTag: 181a2e0a-3e5e-4017-b45a-f49519147748
		summarizeBy: none
		sourceColumn: Número Antigo

		annotation SummarizationSetBy = Automatic

	column Vara
		dataType: string
		lineageTag: 8c97f880-d3e1-4e8f-8a71-f23c26e5fee5
		summarizeBy: none
		sourceColumn: Vara

		annotation SummarizationSetBy = Automatic

	column Autuação
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb84fc2a-2f0e-4d47-972d-70df1e48575e
		summarizeBy: none
		sourceColumn: Autuação

		variation Variation
			isDefault
			relationship: ca5b1966-c26a-45a2-87f9-e40d1c993d2c
			defaultHierarchy: LocalDateTable_80866186-2d35-4e6b-8484-4df18d6b37cb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: d3608367-d317-4f84-86ff-0a8404e5ad67
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Parte
		dataType: string
		lineageTag: 341fb3e1-50bc-45ed-93e1-642e2db8defe
		summarizeBy: none
		sourceColumn: Parte

		annotation SummarizationSetBy = Automatic

	column Entrada
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 710d6fdf-faca-4e3d-b737-400ba28ed080
		summarizeBy: none
		sourceColumn: Entrada

		variation Variation
			isDefault
			relationship: ffded5b0-ab56-4bbe-80df-e3484c97f88d
			defaultHierarchy: LocalDateTable_a5462066-54f5-40ed-a1f3-d06ab2faf2d5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Saída
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b743bf7-2b5a-42c5-a023-9edcfaa12f10
		summarizeBy: none
		sourceColumn: Saída

		variation Variation
			isDefault
			relationship: a4b42bb6-c8fa-4490-887f-7cb336598ce0
			defaultHierarchy: LocalDateTable_e38284cf-46a1-4f3c-b9e3-ba43a860f5f2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Coluna
		type: calculated
		lineageTag: 93b1ae5e-413e-467c-b6b7-864e8a603584
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column 'Idade Processo' =
			
			DATEDIFF('DJR_998'[Entrada], TODAY(), DAY)
		formatString: 0
		lineageTag: 32d1bc4f-b797-4f8e-b249-0e62d417901a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Faixa Tempo' =
			
			SWITCH(
			    TRUE(),
			    'DJR_998'[Idade Processo] <= 90, "Até 3 meses",
			    'DJR_998'[Idade Processo] <= 180, "3 a 6 meses",
			    'DJR_998'[Idade Processo] <= 365, "6 meses a 1 ano",
			    "Mais de 1 ano"
			)
		lineageTag: 8f863642-2592-4830-9dba-0fec3511e877
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DJR_998 = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Palace Hotel\Documents\Banner(IAGO)\Advocacia Sarmento - Copia\1grau.xls"), null, true),
				    DJR_1 = Fonte{[Name="DJR_998"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(DJR_1,{{"Column1", type text}, {"Column2", Int64.Type}, {"Column3", Int64.Type}, {"Column4", type text}, {"Column5", type date}, {"Column6", type text}, {"Column7", type text}, {"Column8", type date}, {"Column9", type date}, {"Column10", type text}}),
				    #"Linhas Superiores Removidas1" = Table.Skip(#"Tipo Alterado",1),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Superiores Removidas1",{"Column1"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Column2", type text}, {"Column3", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado1",{{"Column2", "Número do Processo"}, {"Column3", "Número Antigo"}, {"Column4", "Vara"}, {"Column5", "Autuação"}, {"Column6", "Status"}, {"Column7", "Parte"}, {"Column8", "Entrada"}, {"Column9", "Saída"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas",{"Column10"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"Entrada", type date}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado2",1),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Superiores Removidas", each true),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Linhas Filtradas",{"Column11"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

